// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChu63piinSdK5nIN3Jli0u9reAPqVZRog',
    appId: '1:377973529045:web:1461be56aaaf182cb0c55c',
    messagingSenderId: '377973529045',
    projectId: 'smartac-c3279',
    authDomain: 'smartac-c3279.firebaseapp.com',
    storageBucket: 'smartac-c3279.appspot.com',
    measurementId: 'G-M6DXQDTPHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3AeTO-Xy07VGelz2tybCQghke0po_rQI',
    appId: '1:377973529045:android:e1d668d2e0837731b0c55c',
    messagingSenderId: '377973529045',
    projectId: 'smartac-c3279',
    storageBucket: 'smartac-c3279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjR_g5o_EPvkREyhEzZvKCjRLCOffgPUw',
    appId: '1:377973529045:ios:d7b9f74ca5b30d18b0c55c',
    messagingSenderId: '377973529045',
    projectId: 'smartac-c3279',
    storageBucket: 'smartac-c3279.appspot.com',
    iosBundleId: 'com.example.sac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjR_g5o_EPvkREyhEzZvKCjRLCOffgPUw',
    appId: '1:377973529045:ios:aac9899b9839756ab0c55c',
    messagingSenderId: '377973529045',
    projectId: 'smartac-c3279',
    storageBucket: 'smartac-c3279.appspot.com',
    iosBundleId: 'com.example.sac.RunnerTests',
  );
}
